### PR TITLE
replaces plain txt master file with curated Markdown formatting, pandoc-style yaml metadata, and outputs pdf + html samples

### PR DESCRIPTION
**Pull request by rhythmus**

### CODE REVIEW

**Comment by sethwoodworth** [comment]
Thanks!

Sorry I was terse on twitter.  I would like the history of changing the file from `.txt` to `.md`
- move 10622.txt -> 10622.md
- copy contents of your modified .md including pandoc YAML on top of 10622.txt

This way according to git the new markdown file used to be 10622.txt.  This is important for when we pull new changes from upstream at Project Gutenberg.  If done in this way, copy edits from PG can trickle their way into your markdown file (hopefully).

**Comment by rhythmus** [comment]
No problem — Twitter is terse by design ;-)

I did the commits as requested. I doubt changes from upstream PG will make it through, though. The PG master file is line-wrapped (supporting an old-fashioned reading experience on a terminal?) while best-practices (imho) Markdown formatting of raw text should not line-wrap. Which complicates diffing… (Not to mention encoding issues, such as ascii anemia, non-linux line-endings, utf-8 bit order, etc.)

To avoid unscalable merge conflicts, I guess the GITenberg workflow might want to implement a preprocessing step on new pulls from PG before diffing and merging with its own file base, such as wrapping/unwrapping, removing boilerplate front and backmatter, normalizing encoding, etc.

One may want to have a look at libs such as [GutenMark](http://www.sandroid.org/GutenMark/index.html) and [9-steps tool](http://zenmagiclove.com/hnews/9steps.html).

Or— we forget about backward compatibility, consider GITenberg to be a PG fork, and just accept contributors must use the tools of the new era. (_Kidding._)

Kudos on this great initiative! Looking forward to lots of contributions!

**Comment by sethwoodworth** [comment]
Thank you for replaying these.  I am also not convinced that we'll be able to re-play PG copyedits.  But they happen infrequently enough that we can make them happen by hand.

I would love to automate the first phase of GITenberg conversion (@rsperberg has started in [this repo](https://github.com/gitenberg-dev/scripts)).  [GutenbergCleaner](https://github.com/c-w/GutenbergCleaner) is another example.

FYI, I am leaning _heavily_ towards Asciidoc for the ultimate markup format for the project.  I will be discussing it with the mailing list later this week and writing up a first pass of instructions this weekend. We'd love to have you involved.

**Comment by rhythmus** [comment]
Thanks for merging.

Meanwhile, I subscribed to the [GITenberg mailing list](https://groups.google.com/forum/#!forum/gitenberg-project) and am looking forward to contribute. I know [a few things](https://github.com/rhythmus/markdown-resources/blob/master/lightweightMarkupSyntaxComparison.tsv) about (lightweight) markup languages and believe we could have an interesting discussion.

**Comment by eshellman** [comment]
@rhythmus - great to add your perspective to this problem

**Pull request merged**
